# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc0fca15470883d19567ed9506d5ec3d"
application_url = "https://ho-sufficient-fat-transmitted.trycloudflare.com"
embedded = true
name = "bitssaco"
handle = "bitssaco"

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-4c9539b2.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ho-sufficient-fat-transmitted.trycloudflare.com/auth/callback",
  "https://ho-sufficient-fat-transmitted.trycloudflare.com/auth/shopify/callback",
  "https://ho-sufficient-fat-transmitted.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
